apiVersion: v1
kind: Service
metadata:
  name: coloran-optimizer-service
spec:
  selector:
    app: coloran-optimizer
    version: blue # Initially point to blue, switch to green during deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
