data:
  base_path: /opt/coloran/data
  batch_size: 100000
logging:
  file_path: /var/log/coloran/coloran.log
  level: WARNING
security:
  api_rate_limit: 1000
  input_validation: true
training:
  epochs: 200
  sample_size: 10000000
