name: Comprehensive CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Run unit tests
        run: pytest tests/unit --cov=src
      - name: Run GPU tests
        run: pytest tests/gpu --gpu-required
      - name: Performance benchmarks
        run: python scripts/benchmark.py --compare-baseline
